primary_use_case_description: App para el director de la universidad
user_stories:
- Presentar informacion sobre investigacion y estudiantes
gold_tables:
- serverless_stable_ys5bgd_catalog.puc.gold_estudiante_360_genie
- serverless_stable_ys5bgd_catalog.puc.gold_research_acceleration_cockpit
existing_genies:
- No estoy seguro, quiero que busques.
workflow_requirements: Todas las noches
style_preferences: Glass estilo iPhone 2026
access_requirements: Los directores
style_reference: null
