"""Code generation for Streamlit Databricks Apps.

The bootstrap/skeleton is preferably generated by a real Databricks serving
endpoint (see :meth:`composer.llm.client.LLMClient.generate_app_source`) and
passed in as ``files``. When no model output is available the deterministic
template below is used, so local dev and tests work with no workspace.
"""

from __future__ import annotations

from pathlib import Path

from composer.models.blueprint import AppBlueprint


def _template_files(blueprint: AppBlueprint) -> dict[str, str]:
    return {
        "app.py": (
            "import streamlit as st\n"
            f"st.title('Generated App {blueprint.blueprint_id[:8]}')\n"
            f"st.write('Pages: {', '.join(blueprint.pages)}')\n"
        ),
        "app.yaml": "name: generated-app\ncommand: streamlit run app.py\n",
        "README.md": "# Generated Databricks App\n",
    }


def generate_streamlit_app(
    blueprint: AppBlueprint,
    output_root: str,
    files: dict[str, str] | None = None,
) -> dict:
    """Write the generated app to disk.

    ``files`` maps relative paths to contents (typically produced by the LLM).
    When ``files`` is falsy, a deterministic template is written instead.
    """
    app_dir = Path(output_root) / f"generated_{blueprint.blueprint_id[:8]}"
    app_dir.mkdir(parents=True, exist_ok=True)

    source = "llm"
    contents = files or None
    if not contents:
        contents = _template_files(blueprint)
        source = "template"
    elif "app.py" not in contents:
        # Always guarantee an entrypoint exists.
        contents = {**_template_files(blueprint), **contents}

    written: list[str] = []
    base = app_dir.resolve()
    for rel_path, body in contents.items():
        # Keep paths within the app directory; skip absolute/escaping paths.
        target = (app_dir / rel_path).resolve()
        if base != target and base not in target.parents:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        written.append(str(target))

    return {
        "output_path": str(app_dir),
        "files_generated": written,
        "source": source,
    }
